README.md, format-all.el
It uses sqlformat from the Python package "sqlparse" with some options of choice:
- `-k upper`: to uppercase keywords
- `-a`: to get a multiline, aligned output
=> Define a formatter for SQL (sqlformat)

format-all.el
Quick fix to enable brittany as a formatter for literate haskell files.
=> Formatter for literate haskell

LICENSE, format-all.el
* Include an explicit LICENSE file with the full MIT license text.
* Use the de facto standard "SPDX-License-Identifier" keyword instead
of the "License" keyword (which I think is non-standard and I just
cargo-culted it from some place). SPDX-License-Identifier is not yet
used by Emacs packaging tools but it's used by many other tools.
=> Clarify license

README.md, format-all.el
Hey there 👋 Great package.
This adds support for the [terraform configuration language](https://www.terraform.io/docs/configuration/index.html) by running `terraform fmt -`. 
* Before
```tf
provider "aws" {
region                               = "${var.region}"
shared_credentials_file = "${var.credentials_aws_file}"
profile     = "tf"
version                    = "~> 2.5"
}
```
* After
```tf
provider "aws" {
region                  = "${var.region}"
shared_credentials_file = "${var.credentials_aws_file}"
profile                 = "tf"
version                 = "~> 2.5"
}
```
=> Support Terraform via 'terraform fmt'

README.md, format-all.el
Adds support for Bazel Starlark (https://docs.bazel.build/versions/master/skylark/language.html) using buildifier (https://github.com/bazelbuild/buildtools/tree/master/buildifier)
=> Add support for Bazel Starlark using buildifier

format-all.el
I encountered the following error when formatting a YAML file with yq:
jq: error: read/0 is not defined at <top-level>, line 1:
read
jq: 1 compile error
Because the formatter yq use the wrong arguments, the "read" argument must change to ".",
see https://github.com/kislyuk/yq/issues/50 for more information.
Because prettier already support formatting YAML, switch to it is better, this
also solve the issue https://github.com/lassik/emacs-format-all-the-code/issues/39
=> fix: switch YAML from yq to prettier.

README.md, format-all.el
Added support for formatting fish shell code using the built-in [fish_indent](https://fishshell.com/docs/current/commands.html#fish_indent)
=> add fish shell support

format-all.el
fix #62 
Log when format:
```
;; project with .formatter.exs in subdirectory
Format-All: Formatting create_users.exs as (mix-format t)
Format-All: Running: /Users/james/.asdf/shims/mix format --dot-formatter \~/src/elixir_formatter_playground/priv/subdir/.formatter.exs -
Format-All: Directory: ~/src/elixir_formatter_playground/
;; project without any .formatter.exs
Format-All: Formatting format.ex as (mix-format t)
Format-All: Running: /Users/james/.asdf/shims/mix format -
Format-All: Directory: /Users/james/.asdf/installs/elixir/1.9.4-otp-22/lib/mix/lib/mix/tasks/
```
=> Fix mix format ignores config in subdirectories

format-all.el
Prettier now has a "html" parser for plain HTML, so both prettier and
html-tidy can format HTML. Format-all currently has rules only for
html-tidy in Emacs' own HTML modes, but has rules for both html-tidy
and prettier in web-mode. By accident, prettier's web-mode rule had
precedence over the html-tidy rule, which would mean that HTML is
sometimes formatted with html-tidy (if you happen to be in html-mode)
but the same HTML file is formatted with prettier instead if you
happen to be in web-mode. That difference is confusing for users.
Solve the problem by disabling prettier for plain HTML. In the future,
the proper fix will be to have multi-formatter support, and support
both prettier and html-tidy in all HTML-related Emacs modes. Then
people can choose which formatter they want.
=> Fix prettier vs html-tidy conflict in web-mode

format-all.el
The React layer for Spacemacs defines `react-mode`. Add support for formatting `react-mode` buffers.
=> Add support for react-mode

format-all.el
When formatting Swift code, the `*format-all-errors*` buffer displays:
```
Running SwiftFormat...
Swiftformat completed successfully.
```
Using the `--quiet` flag disables this message. Only error messages will be displayed.
=> Use "--quiet" option for swiftformat

format-all.el
The homebrew version of scalafmt is out of date and not the recommended way to
install scalafmt. It does not properly support the `--quiet` flag, leading to
output of `Reformatting...` on `stderr`, which gets reported as an error. The
most recent version fixes this, and can be installed cross platform using
`coursier`.
=> Fix scalafmt output issue

format-all.el
=> Use cargo fmt instead of rustfmt

README.md, format-all.el
[Gleam](https://gleam.run/) is a statically typed functional language for the BEAM.
=> Support Gleam

format-all.el
Fixes this error when byte-compiling:
```
In toplevel form:
format-all.el:138:66:Error: Symbol’s function definition is void: windows-nt
```
=> Add (require 'cl-lib)

format-all.el
format-all--resolve-system and format-all--system-type should be available in runtime.
=> Make define-format-all-formatter available to users

format-all.el
This fixes byte-compiling broken by #101.
=> Revert the last change (f2a36ab1) and use eval-and-compile instead

format-all.el
Error output is often ignorable if you are using a lint tool purely as a formatter.  This new tunable prevents informative messages and warnings from distracting you.
=> Add a custom variable format-all-show-errors-on-success

format-all.el
Uses the new `-filename` option of shfmt 3.2.0.  We must avoid passing `-ln` when passing `-filename` because no options are read from `.editorconfig` if any options are passed on the command line.
Fixes #90.
=> shfmt: Respect .editorconfig configuration

README.md, format-all.el
`goimports` is a pretty popular alternative for `gofmt`. It automatically adds/removes import lines along with formatting the code.
https://godoc.org/golang.org/x/tools/cmd/goimports
=> Add goimports as a go formatter

format-all.el
Prior to this, .prettierignore was only loaded if it was directly adjacent to the file being formatted
WDYT to this?
=> Support .prettierignore files

README.md, format-all.el
This commit adds nixpkgs-fmt formatter and makes it default nix formatter. I suggest making it default as it's the standard used by nixpkgs. Everything seems to be working, but feedback is appreciated. 
Thanks for this awesome package!
=> Add nixpkgs-fmt and make it default

README.md, format-all.el
This change adds support for ReScript using `bsc -format` through
resfmt.
Depends-On: https://github.com/lassik/emacs-language-id/pull/6
=> Add ReScript

format-all.el
That's what I suggested in #140 :)
=> Customize error symbol when formatter not found

README.md, format-all.el
Adds support for https://github.com/fourmolu/fourmolu for Haskell code. Not sure why the cabal-fmt commit is here, something strange must have happened when I synced my fork with master. Let me know if you'd like me to clean the history up before merging.
=> Fourmolu support

format-all.el
This change removes the resfmt wrapper since rescript now support stdin.
=> Use the official ReScript CLI

README.md, format-all.el
This will work properly when language-id-buffer correctly identifies Cuda. I have a separate PR on your other repo adding support for Cuda there
=> Use clang-format for Cuda

format-all.el
Without this, Rubocop (which is what StandardRB uses under the hood)
outputs everything to stdout, including a line of several "="
characters. StandardRB is smart enough to filter a majority of this
output, but not that line of "=" characters, which then makes its way to
the formatted file in emacs' buffer. This fixe the issue.
Closes issue #156.
=> Add --stderr to StandardRB formatter command

README.md, format-all.el
I have not changed the default to the new one, let me know if that should be done. 
For anyone else running into this, you can change the formatter using: 
```emacs-lisp
(setq-default format-all-formatters '(("Dart" dart-format)))
```
ref: https://github.com/lassik/emacs-format-all-the-code/issues/130
=> Add `dart format` as a formatter for dart

format-all.el
As stated in the R manual[1], the flag `--vanilla` stands for --no-site-file,
--no-init-file, --no-environ and (except for R CMD) --no-restore.
In sum, no user environment can be loaded using that flag, as reported here[2].
When removed, the command `format-all-buffer` works as expected in the ess-mode.
[1]: https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html
[2]: https://github.com/lassik/emacs-format-all-the-code/issues/76#issuecomment-591465281
Related to #76
=> get R user environment

README.md, format-all.el
This adds support for formatting via ts-standard (TypeScript version of https://standardjs.com/)
=> Add TypeScript formatting via `ts-standard`

README.md, format-all.el
The currently supported [node-cljfmt](https://github.com/snoe/node-cljfmt) has been recently deprecated, so I added support for the competing project [zprint](https://github.com/kkinnear/zprint). I haven't changed the default, but I think zprint deserves to be the default since it supports [Babashka](https://babashka.org/) scripts and is more configurable.
Let me know what you think :)
=> Add Clojure formatter `zprint`

format-all.el
There seems to be an assert for this field to exist, and so evaluating the file doesn't work without this.
=> Add missing features field to Zig formatter

README.md, format-all.el
Hi, thank you for creating this useful package.
I'd like to add Erlang support to this package.
This PR adds [efmt](https://github.com/sile/efmt) as the formatter for Erlang code (BTW, I'm the author of this formatter).
However, `efmt` is not a famous Erlang formatter. So I'm willing to close this PR if you want to avoid using such a formatter.
Related PR: https://github.com/lassik/emacs-language-id/pull/15
=> Add efmt (an Erlang formatter)

README.md, format-all.el
Couldn't find any guidelines to contributing so my apologies if something is not handled properly.
- Added matcher to match files ending in `.erb` to the `_Erb` language (which was unsupported before).
- Adds support for [erb-formatter](https://github.com/nebulab/erb-formatter) to format `_Erb` files.
I decided to use `_Erb` as the language-id as Github does not seem to have an official title for the language, instead identifying it as `HTML+ERB`.
=> Add erb formatter support

format-all.el
Alternative impelementation of PR #195
See also:
- Issue #175
- PR #190, #182
=> Let Prettier infer the parser when it can

format-all.el
This change enables using the latest formater version by fixing
this error:
The --stdin-input-file option is necessary when using input
from stdin and accounting for .cabal files
=> Support fourmolu version 0.8

format-all.el
Fixes #191 . One does not require `diminish` to hide lighters anymore.
=> Provide a customizable lighter for format-all-mode

format-all.el
Clarify that you can specify custom arguments to pass to each formatter.
=> Improve format-all-default-formatters customization

format-all.el
It is often called before calling format-all-mode, so it'd be nice if autoloading covered it.
=> Add autoload for format-all-ensure-formatter

format-all.el
`--stdin-filename` is necessary for HEEX and should not make a difference for other Elixir files, ref:
https://hexdocs.pm/mix/1.14.1/Mix.Tasks.Format.html
Requires at least Elixir 1.14.0 and for HEEX templates the correct `.formatter.exs` configuration: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-setup
goes along: https://github.com/lassik/emacs-language-id/pull/23
=> Add support for HTML+EEX

README.md, format-all.el
Adding this [csharpier](https://github.com/belav/csharpier) as the default formatter for C# files.
=> Adding csharpier to format-all

README.md, format-all.el
Add formatting support for [Ruby syntax_tree](https://github.com/ruby-syntax-tree/syntax_tree) using the `stree format` command.
=> Add syntax_tree formatter

README.md, format-all.el
Added a `format-all-region-or-buffer` command. I don't know any reason to not have it, and the benefit is that you can bind it to a single key and it'll do the right thing.
I used the suffix `-region-or-buffer`rather than `-buffer-or-region` for consistency with the `elisp-eval-region-or-buffer` function introduced in Emacs 29.1
=> Add format-all-region-or-buffer command

format-all.el
The current code has a bug where given that:
1. You're editing a file that uses tabs for indentation; and
2. You run either `format-all-buffer` or `format-all-region` and the command exits with an error, with no changes to the buffer
Then point will be moved a little to the right (depending on your width of tab). Since there are no changes to the code, the expected result would be that point stays in same place.
The reason for that is the code adds the old value of current-column to point, but point and column are not equivalent, because column is based on the width of a given character. For example, when you move through a tab character, point increases by 1 but column will increase by 8 (or whichever is the configured width for tabs).
So I fixed that and added a note in the code.
minor: …
=> Fix format-all--save-line-number column logic

format-all.el
By default, perltidy writes errors to a file called `perltidy.ERR`. To make it write to stderr (which is what is assumed by format-all), we need to pass a "--standard-error-output" flag.
=> Fix perltidy error output

format-all.el
So that commands like `indent-pp-sexp` will indent the macro correctly.
=> minor: Declare indent of define-format-all-formatter

format-all.el
This makes it so pressing `q` will kill the window, and it respects the customizable variable `help-window-select`.
---
With the current behavior, when format-all displays an error, I have to `C-x o` into the new window it created, and kill it with `C-x k`. I think the usability is much better if we display the error buffer in a help-like window. What do you think, @lassik ?
=> minor: Display error buffer with with-help-window

format-all.el
Sometimes, scalafmt does not produce formatted output to stdout with only the `--stdin` flag provided. For example, this happens when there are no formatting changes required to be made to the file. As-is, this causes the formatter to clear the buffer when there are no formatting changes required.
As a workaround, adding the `--stdout` flag ensures that output is always put on stdout.
See https://github.com/scalameta/scalafmt/issues/3632 for more information.
=> scalafmt: Add --stdout as workaround for odd behaviour

format-all.el
`ktlint` now prints info logs by default, we have to disable logging when using the formatter.
sadly the new cli arg for disabling logging has not been released yet, so I'll leave this in _draft_ until it has.
=> fix (kotlin linter): remove log files from output

README.md, format-all.el
The PR adds support for formatting hashcorp hcl files with the help of `hclfmt`.
Tested it with `M-x load-file` and running `format-all-buffer`.
=> Add formatter: hclfmt for hashicorp HCL files.

README.md, format-all.el
add built-in support for google-java-format for java.
If it sounds good to you, I can further update default formatter of java to this one. google-java-format seems to be the most adopted formatter nowadays.
=> feat: add google-java-format for java

format-all.el
Current configuration for `cljfmt` is broken. This PR fixes it.
=> Fix cljfmt
