lassik/emacs-format-all-the-code

- README.md
- format-all.el
This is just a suggestion. We might need more minor modes if we want to support all languages and different formaters for one language.
> add minor mode support

- README.md
- format-all.el
Thanks for an awesome and much needed Emacs library!
> Support Lua via lua-fmt

- format-all.el
> Add cperl-mode support

- format-all.el
Support [ledger-mode](https://github.com/ledger/ledger-mode)
> ledger-mode support

- README.md
- format-all.el
This PR adds support for LaTeX (via `latexindent`) and BibTeX (via `bibtex-mode`).
> LaTeX and BibTeX support

- README.md
- format-all.el
Prettier has a plugin for support PHP: https://github.com/prettier/plugin-php
> Support PHP

- README.md
- format-all.el
https://github.com/r-lib/styler/issues/517
Related issue. I was using reformatter for styler but I think adding it here would be better. Feel free to fix the formatting, I couldn't find a good example of something that didn't have an executable.
> WIP: add initial styler formatter

- README.md
- format-all.el
Support the default scala formatter `scalafmt`.
> Add support for Scalafmt

- README.md
- format-all.el
I messed up the merging of #71 by @tenniscp25. This PR is another attempt.
> Add support for purescript with purty

- README.md
- format-all.el
Add Solidity support with Prettier.
- https://prettier.io/
- https://github.com/prettier-solidity/prettier-plugin-solidity
> Add support for Solidity with Prettier

- format-all.el
This is a big change. Previously format-all had a (:modes ...)
specification for each supported formatter. The :modes specs started
to accumulate increasingly crufty rules for detecting the language
based on the major mode, minor modes and other variables.
That cruft has now been spun off into the language-id library, which
can also be used by other packages besides format-all, and has the
luxury of using a less crufty format for its specifications. Unlike
format-all's labyrinthine 'prettier' definition, language-id's source
code is readable by humans.
> Use language-id library to detect languages

- format-all.el
> More languages

- README.md
- format-all.el
Depends on https://github.com/lassik/emacs-language-id/pull/3
> Support cabal-fmt for Haskell-Cabal mode

- format-all.el
> Explicitly require "inheritenv"

- README.md
- format-all.el
adds more options to control displaying the errors buffer
> more control over errors buffer displaying

- format-all.el
- Use `regexp-opt` instead of obsolete `regexp-or` (fixes #144)
- Fix execution with Bundler by removing the directory part from `executable`
> Fix the ruby formatters

- README.md
- format-all.el
Requires https://github.com/lassik/emacs-language-id/pull/7.
> Add Svelte support

- README.md
- format-all.el
This is also (hopefully) fairly straightforward
> Add support for F# using fantomas

- README.md
- format-all.el
isort[0] helps to sort and format imports.
0: https://github.com/PyCQA/isort
> Add isort for Python

- README.md
- format-all.el
> Support `taplo fmt` for TOML

- README.md
- format-all.el
Thank you!
as for the new formatter: https://github.com/chipsalliance/verible/tree/master/verilog/tools/formatter
> Add `Verible` as a Verilog formatter.

- README.md
- format-all.el
I reproduced #179 and made minor improvements.
Credit to @jeongsoolee09
> Add `ocamlformat` as an OCaml formatter

- format-all.el
> Change ormolu formatter to use --stdin-input-file

- format-all.el
> Save and restore the marker and mark-ring when formatting

- README.md
I am sharing what I have learned
> Added example using use-package

- README.md
- format-all.el
> Deprecate node-cljfmt
